### ISSUE TITLE
OAuth fails if GitHub user's email address is hidden

### ISSUE THREAD

**Issue by ktbartholomew** [smashwilson/strider-github-auth#8]
The OAuth process fails [right about here](https://github.com/smashwilson/strider-github-oauth/blob/master/authorization.js#L28) if a GitHub user's profile is set not to display their email address:

![image](https://cloud.githubusercontent.com/assets/3018940/13996808/4614a462-f0fd-11e5-944b-e3c4a22bea96.png)

**Comment by smashwilson** [comment]
Weird - I'm having trouble reproducing this. Even if I turn up all of the email address privacy settings in my GitHub profile, I still see `emails` in my profile JSON.

**Comment by smashwilson** [comment]
Ohhh, I bet I know what's happening - the application that we're using for Nexus probably doesn't request an email scope.

**Comment by smashwilson** [comment]
Maybe?

![screen shot 2016-03-25 at 9 49 11 am](https://cloud.githubusercontent.com/assets/17565/14045249/ecbc14d6-f26e-11e5-8263-350d3f1d9eef.jpeg)

**Comment by smashwilson** [comment]
No, that's not it - the scopes are listed in code and definitely include `user:email`.

Well, I can test for profiles missing an `email` key whether or not I can reproduce it in production. There's another API call I can use to enumerate email addresses.

Fake edit: Yeah, email is [supposed to be `null`](https://developer.github.com/v3/users/#get-a-single-user) if you don't specify a public email address. I bet I'm hitting some caching issues.
